require('./login.js')
require('./logout.js')
require('./create-account.js')
require('./create-comment.js')
require('./create-game.js')
require('./create-post.js')
require('./make-toast.js')
require('./add-game-button.js')